/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PPE_Inventory_Management_System;

import java.awt.CardLayout;

/**
 *
 * @author user
 */
public class Staff_Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Staff_Main () {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideNavPanel = new javax.swing.JPanel();
        StaffDashboardBtn = new javax.swing.JButton();
        StaffSupplierBtn = new javax.swing.JButton();
        StaffHospitalBtn = new javax.swing.JButton();
        StaffReportBtn = new javax.swing.JButton();
        StaffTransactionBtn = new javax.swing.JButton();
        StaffLogOutBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supplierPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        hospitalPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        transactionPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PPE Inventory Management System");
        setBackground(new java.awt.Color(238, 245, 255));
        setBounds(new java.awt.Rectangle(280, 100, 899, 579));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 650));

        SideNavPanel.setBackground(new java.awt.Color(255, 255, 255));

        StaffDashboardBtn.setText("Dashboard");
        StaffDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffDashboardBtnActionPerformed(evt);
            }
        });

        StaffSupplierBtn.setText("Supplier Management");
        StaffSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffSupplierBtnActionPerformed(evt);
            }
        });

        StaffHospitalBtn.setText("Hospital Management");
        StaffHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffHospitalBtnActionPerformed(evt);
            }
        });

        StaffReportBtn.setText("Report");
        StaffReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffReportBtnActionPerformed(evt);
            }
        });

        StaffTransactionBtn.setText("Transaction");
        StaffTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffTransactionBtnActionPerformed(evt);
            }
        });

        StaffLogOutBtn.setText("Log Out");
        StaffLogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffLogOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideNavPanelLayout = new javax.swing.GroupLayout(SideNavPanel);
        SideNavPanel.setLayout(SideNavPanelLayout);
        SideNavPanelLayout.setHorizontalGroup(
            SideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideNavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StaffReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(StaffSupplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StaffDashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(StaffHospitalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(StaffTransactionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(StaffLogOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );
        SideNavPanelLayout.setVerticalGroup(
            SideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideNavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StaffDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StaffSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StaffHospitalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StaffReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StaffTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StaffLogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        dashboardPanel.setPreferredSize(new java.awt.Dimension(670, 560));

        jLabel1.setText("here is dashboard");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(517, Short.MAX_VALUE))
        );

        MainPanel.add(dashboardPanel, "dashboardPanel");

        supplierTable.setAutoCreateRowSorter(true);
        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"S001", "Tom", "012-3456789", "tom@gmail.com", "18, abcde, 14000 New York", "Head Cover"},
                {"S002", "Jerry", "012-3456789", "jerry@gmail.com", "23, defg, 47180 USA", "Face Shield, Mask"},
                {"S003", "Peter", "012-3456789", "peter@gmail.com", "85, hijk, 57600 Masjid Jamek", "Gloves"},
                {"S004", "Jane", "012-3456789", "jane@gmail.com", "105, Taman Equine, 24678, Damansara ", "Gown, Shoe Covers"}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "Contact", "Email", "Address", "PPE Supplies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplierTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        supplierTable.setColumnSelectionAllowed(true);
        supplierTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        supplierTable.setGridColor(new java.awt.Color(0, 0, 0));
        supplierTable.setRowHeight(30);
        supplierTable.setRowSelectionAllowed(false);
        supplierTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        supplierTable.setShowGrid(true);
        supplierTable.setShowVerticalLines(true);
        supplierTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(supplierTable);
        supplierTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (supplierTable.getColumnModel().getColumnCount() > 0) {
            supplierTable.getColumnModel().getColumn(0).setResizable(false);
            supplierTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            supplierTable.getColumnModel().getColumn(1).setResizable(false);
            supplierTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            supplierTable.getColumnModel().getColumn(2).setResizable(false);
            supplierTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            supplierTable.getColumnModel().getColumn(3).setResizable(false);
            supplierTable.getColumnModel().getColumn(3).setPreferredWidth(130);
            supplierTable.getColumnModel().getColumn(4).setResizable(false);
            supplierTable.getColumnModel().getColumn(4).setPreferredWidth(200);
            supplierTable.getColumnModel().getColumn(5).setResizable(false);
            supplierTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setLabelFor(supplierTable);
        jLabel2.setText("Supplier Details");

        javax.swing.GroupLayout supplierPanelLayout = new javax.swing.GroupLayout(supplierPanel);
        supplierPanel.setLayout(supplierPanelLayout);
        supplierPanelLayout.setHorizontalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
        );
        supplierPanelLayout.setVerticalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        MainPanel.add(supplierPanel, "supplierPanel");

        jLabel3.setText("here is hospital panel");

        javax.swing.GroupLayout hospitalPanelLayout = new javax.swing.GroupLayout(hospitalPanel);
        hospitalPanel.setLayout(hospitalPanelLayout);
        hospitalPanelLayout.setHorizontalGroup(
            hospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalPanelLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        hospitalPanelLayout.setVerticalGroup(
            hospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hospitalPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addContainerGap(502, Short.MAX_VALUE))
        );

        MainPanel.add(hospitalPanel, "hospitalPanel");

        jLabel4.setText("here is report panel");

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel4)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        MainPanel.add(reportPanel, "reportPanel");

        jLabel5.setText("here is transaction panel");

        javax.swing.GroupLayout transactionPanelLayout = new javax.swing.GroupLayout(transactionPanel);
        transactionPanel.setLayout(transactionPanelLayout);
        transactionPanelLayout.setHorizontalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        transactionPanelLayout.setVerticalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel5)
                .addContainerGap(468, Short.MAX_VALUE))
        );

        MainPanel.add(transactionPanel, "transactionPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SideNavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SideNavPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StaffSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffSupplierBtnActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "supplierPanel");
        
//        supplierTable.getColumn(0).setPreferredWidth(100);
//        supplierTable.getColumn(1).setPreferredWidth(200);
//        supplierTable.getColumn(2).setPreferredWidth(100);
//        supplierTable.getColumn(3).setPreferredWidth(100);
//        supplierTable.getColumn(4).setPreferredWidth(100);
//        supplierTable.getColumn(5).setPreferredWidth(100);
    }//GEN-LAST:event_StaffSupplierBtnActionPerformed

    private void StaffReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffReportBtnActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "reportPanel");
    }//GEN-LAST:event_StaffReportBtnActionPerformed

    private void StaffDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffDashboardBtnActionPerformed
        
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "dashboardPanel");
    }//GEN-LAST:event_StaffDashboardBtnActionPerformed

    private void StaffHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffHospitalBtnActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "hospitalPanel");
    }//GEN-LAST:event_StaffHospitalBtnActionPerformed

    private void StaffTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffTransactionBtnActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "transactionPanel");
    }//GEN-LAST:event_StaffTransactionBtnActionPerformed

    private void StaffLogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffLogOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffLogOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run () {
                new Staff_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SideNavPanel;
    private javax.swing.JButton StaffDashboardBtn;
    private javax.swing.JButton StaffHospitalBtn;
    private javax.swing.JButton StaffLogOutBtn;
    private javax.swing.JButton StaffReportBtn;
    private javax.swing.JButton StaffSupplierBtn;
    private javax.swing.JButton StaffTransactionBtn;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel hospitalPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel supplierPanel;
    private javax.swing.JTable supplierTable;
    private javax.swing.JPanel transactionPanel;
    // End of variables declaration//GEN-END:variables
}
